server:
  port: 8083

spring:
  application:
    name: note-service

  datasource:
    url: jdbc:mysql://localhost:8889/db_notes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info
